# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d15ed8cfeaf0d06e211db182e6cdea10b61a2f23008c861f5fc117aa00b872c7bb3c3939808ffd30a713f453188fe4a447b68a850d7c99920cea8f859f6be30

test:
  secret_key_base: f8f7dcced2807ac945c11ea45f6800b1b1e28ce36f08f55b38a9938f2564284392c39986a11e8b9f9e17884ac6b133002d6831c2d40b5c62fe40af18c2cf0142

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
